id = "ltex"
name = "ltex"
version = "0.0.3"
description = "LTEX+ Language Server support for Zed editor"
schema_version = 1
authors = ["Vitaly Slobodin <vitaliy.slobodin@gmail.com>"]
repository = "https://github.com/vitallium/zed-ltex"

[language_servers.ltex]
name = "LTeX"
languages = [
  "LaTeX",
  "Markdown",
  "Plain Text",
  "reST",
  "Git Commit",
  "HTML",
  "Typst",
]
